import type { Metadata } from "next";
import "./globals.css";
import {ReactNode} from "react";
import {Navbar} from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full h-full bg-white dark:bg-black`}
      >
      <Navbar />
        {children}
      </body>
    </html>
  );
}
